spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      read-write: jdbc:mysql://localhost:3306/thinner?zeroDateTimeBehavior=convertToNull
      read-only: jdbc:mysql://localhost:3306/thinner?zeroDateTimeBehavior=convertToNull
    username: root
    password: gabriella93
    hikari:
      maximum-pool-size: 30
      auto-commit: false
      connection-init-sql:

server:
  port: 8080

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: validate  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
    open-in-view: false
  output:
    ansi:
      enabled: always
logging:
  config: classpath:log4j2-local.xml