spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      read-write: jdbc:mysql://localhost:3306/thinner?zeroDateTimeBehavior=convertToNull
      read-only: jdbc:mysql://localhost:3306/thinner?zeroDateTimeBehavior=convertToNull
    username: root
    password: gabriella93
    hikari:
      maximum-pool-size: 30
      auto-commit: false
      connection-init-sql:
  jwt:
    expire:
      accessTokenValidMilliSeconds: 60000  #60 x 10 x 1000 : 1분
      refreshTokenValidMilliSeconds: 604800000 #60 x 60 x 24 x 7 x 1000 : 1주
  data:
    redis:
      host: localhost
      port: 6379
      
server:
  port: 8083

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: validate  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
    open-in-view: false
  output:
    ansi:
      enabled: always
logging:
  config: classpath:log4j2-local.xml

